anchor_version = "0.23.0"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
multisig = "6tbPiQLgTU4ySYWyZGXbnVSAEzLc1uF8t5kJPXXgBmRP"

[programs.devnet]
multisig = "FeqQXwTJvmt6YbLTzibZJVvDFq3tKp49zjWkPqDk7oZJ"

[programs.localnet]
multisig = "6tbPiQLgTU4ySYWyZGXbnVSAEzLc1uF8t5kJPXXgBmRP"

[scripts]
test = "npx mocha -t 1000000 tests/"
